---
- hosts: all
  tasks:
    - apt: name={{item}} update_cache=yes
      with_items:
        - autoconf
        - build-essential
        - g++
        - libavahi-client-dev
        - libavahi-common-dev
        - libsensors4-dev
        - libsqlite3-dev
        - libssl-dev
        - libxml2-dev
    - stat: path=/usr/local/bin/istatserver
      register: istatbin
    - get_url: url="https://s3.amazonaws.com/bjango/files/istatserverlinux/istatserver-3.01.tar.gz" dest=/tmp
      when: istatbin.stat.exists == False
    - command: tar xvzf /tmp/istatserver-3.01.tar.gz
      args:
        chdir: /tmp
      when: istatbin.stat.exists == False
    - shell: "./autogen && ./configure && make && make install"
      args:
        chdir: /tmp/istatserver-3.01
      when: istatbin.stat.exists == False
    - shell: "ps aux | grep istatserver | grep -v grep"
      ignore_errors: yes
      register: istatproc
    - command: "/usr/local/bin/istatserver -d"
      when: istatproc.rc != 0